CREATE DATABASE 1ST;
USE 1ST;

CREATE TABLE USERS(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(150) UNIQUE NOT NULL,
    GENDER ENUM("MALE","FEMALE","OTHER"),
    DATE_OF_BIRTH DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

-- ALTER TABLE USERS ADD COLUMN IS_ACTIVE BOOLEAN DEFAULT TRUE;
-- ALTER TABLE USERS DROP COLUMN IS_ACTIVE;
-- ALTER TABLE USERS MODIFY COLUMN EMAIL VARCHAR(150) AFTER ID;

INSERT INTO USERS VALUES
	(2251081135,"rafiulislam7351@gmail.com","Rafiul Islam","Male","2005-08-01",DEFAULT);

SELECT * FROM USERS;
-- RENAME TABLE USERS TO MASTERS;
DROP TABLE USERS;
DROP DATABASE 1ST;