CREATE DATABASE UTTARA_UNIVERSITY;
USE UTTARA_UNIVERSITY;

CREATE TABLE DEPARTMENT(ID INT PRIMARY KEY, COURSES VARCHAR(70));
INSERT INTO DEPARTMENT(ID,COURSES) VALUES
	(101,"STRUCTURED PROGRAMMING LANGUAGE"),
	(102,"STRUCTURED PROGRAMMING LANGUAGE LAB"),
	(103,"DISCRETE MATHEMATICS"),
	(104,"DISCRETE MATHEMATICS LAB"),
	(105,"DATA STRUCTURE AND ALGORITHMS"),
	(106,"DATA STRUCTURE AND ALGORITHMS LAB");

CREATE TABLE TEACHERS(ID INT PRIMARY KEY,NAME VARCHAR(30),DEPARTMENT_ID INT,
FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
);
INSERT INTO TEACHERS(ID,NAME,DEPARTMENT_ID) VALUES
	(1100,"JBFKJSBKJSN",101),
    (1010,"SJFHJNVKJ,SN",104),
    (1110,"SKJCHBIB",102),
    (1111,"JHACBJBCJ",106);

UPDATE DEPARTMENT SET ID=109
WHERE ID=106;

DELETE FROM DEPARTMENT WHERE ID=105;
SELECT * FROM TEACHERS ORDER BY ID ASC;
SELECT * FROM DEPARTMENT ORDER BY ID ASC;
SELECT * FROM TEACHERS AS T INNER JOIN DEPARTMENT AS D ON T.DEPARTMENT_ID = D.ID;

SELECT * FROM TEACHERS AS T LEFT JOIN DEPARTMENT AS D ON T.DEPARTMENT_ID = D.ID
UNION
SELECT * FROM TEACHERS AS T RIGHT JOIN DEPARTMENT AS D ON T.DEPARTMENT_ID = D.ID;



