CREATE DATABASE UU;
USE UU;

CREATE TABLE DEPARTMENT(ID INT PRIMARY KEY, COURSES VARCHAR(70));
INSERT INTO DEPARTMENT(ID,COURSES) VALUES
	(101,"STRUCTURED PROGRAMMING LANGUAGE"),
	(102,"STRUCTURED PROGRAMMING LANGUAGE LAB"),
	(103,"DISCRETE MATHEMATICS"),
	(104,"DISCRETE MATHEMATICS LAB"),
	(105,"DATA STRUCTURE AND ALGORITHMS"),
	(106,"DATA STRUCTURE AND ALGORITHMS LAB");

ALTER TABLE DEPARTMENT ADD COLUMN CREDIT INT;

ALTER TABLE DEPARTMENT DROP COLUMN CREDIT;

ALTER TABLE DEPARTMENT RENAME NAME_OF_COURSE;

ALTER TABLE NAME_OF_COURSE CHANGE COURSES COURSE_NAME VARCHAR(50);

ALTER TABLE NAME_OF_COURSE MODIFY COURSE_NAME VARCHAR(70);
TRUNCATE TABLE NAME_OF_COURSE;
SELECT * FROM NAME_OF_COURSE;