CREATE DATABASE SCHOOL;
USE SCHOOL;

CREATE TABLE STUDENT(ID INT PRIMARY KEY, NAME VARCHAR(70),AGE INT,LOCATION VARCHAR(70));
INSERT INTO STUDENT(ID,NAME,AGE,LOCATION) VALUES
	(101,"SUMON",21,"KAMARPARA"),
	(102,"SHAKIL",20,"KAMARPARA"),
	(103,"SHAGOR",22,"BHUSHURMILL");

ALTER TABLE STUDENT CHANGE NAME FULL_NAME VARCHAR(50);
ALTER TABLE STUDENT ADD COLUMN MARKS INT NOT NULL DEFAULT 79;

SET SQL_SAFE_UPDATES=1;
DELETE FROM STUDENT WHERE MARKS<80;

SELECT * FROM STUDENT;